#!/bin/bash
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
#
# run.sh - Launch the S-CORE Lifecycle Launch Manager with Pullpiri components
#
# This script builds the Pullpiri lifecycle configuration, copies the compiled
# Flatbuffer binaries and logging configs into the correct locations, and then
# starts the Launch Manager daemon.
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Determine workspace root
if [ -n "$BUILD_WORKSPACE_DIRECTORY" ]; then
    WORKSPACE_ROOT="$BUILD_WORKSPACE_DIRECTORY"
else
    # Assume we are inside examples/pullpiri_LM/
    WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
fi

BAZEL_BIN="$WORKSPACE_ROOT/bazel-bin"
LM_BINARY="$BAZEL_BIN/src/launch_manager_daemon/launch_manager"
CFG_DIR="$BAZEL_BIN/examples/pullpiri_LM/flatbuffer_out"
ETC_DIR="$WORKSPACE_ROOT/etc"

# mini-adas source workspace (relative to this repo)
MINI_ADAS_DIR="$(cd "$WORKSPACE_ROOT/../../feo" && pwd)"
MINI_ADAS_LIB="$MINI_ADAS_DIR/examples/rust/mini-adas/lib"

echo "============================================="
echo "  Pullpiri Lifecycle - Build & Run"
echo "============================================="

# ---- Step 1: Build ----
echo ""
echo "[1/5] Building S-CORE Lifecycle with Pullpiri config..."
cd "$WORKSPACE_ROOT"
bazel build --config=x86_64-linux //examples/pullpiri_LM:pullpiri_config //src/launch_manager_daemon:launch_manager

# ---- Step 1.5: Build mini-adas with lifecycle feature ----
echo ""
echo "[1.5/5] Building mini-adas (adas_primary + adas_secondary) with lifecycle feature..."
cd "$MINI_ADAS_DIR/examples/rust/mini-adas"

# cargo clean
# Back up the header first!
sudo cp /usr/include/linux/stddef.h /usr/include/linux/stddef.h.bak
 
# Change 'long' to 'unsigned long' to match Clang's expectation
sudo sed -i 's/typedef long size_t;/typedef unsigned long size_t;/g' /usr/include/linux/stddef.h

LIBRARY_PATH="$MINI_ADAS_LIB" cargo build --release \
    --bin adas_primary --bin adas_secondary \
    --features "signalling_relayed_tcp,lifecycle" 2>&1 | grep -v "^warning"
cd "$WORKSPACE_ROOT"
ADAS_RELEASE="$MINI_ADAS_DIR/target/release"

# Install mini-adas binaries and shared libraries to /opt/pullpiri
sudo cp "$ADAS_RELEASE/adas_primary"   /opt/pullpiri/bin/adas_primary
sudo cp "$ADAS_RELEASE/adas_secondary" /opt/pullpiri/bin/adas_secondary
sudo chmod +x /opt/pullpiri/bin/adas_primary /opt/pullpiri/bin/adas_secondary
sudo cp "$MINI_ADAS_LIB"/lib*.so /opt/pullpiri/lib/
echo "  mini-adas binaries and .so installed to /opt/pullpiri"

# ---- Step 2: Copy flatbuffer configs ----
echo ""
echo "[2/5] Copying compiled Flatbuffer configs to $ETC_DIR ..."
mkdir -p "$ETC_DIR"
sudo cp "$CFG_DIR/lm_demo.bin"                 "$ETC_DIR/lm_demo.bin"
sudo cp "$CFG_DIR/hm_demo.bin"                 "$ETC_DIR/hm_demo.bin"
sudo cp "$CFG_DIR/hmcore.bin"                  "$ETC_DIR/hmcore.bin"
# hmproc_adas_primary.bin is regenerated by Bazel with the correct "adas_primary"
# identifier (the pre-built one from the other system uses the wrong "mini_adas_primary").
# mini-adas is a Rust app so it does NOT read CONFIG_PATH / hmproc_*.bin itself, but we
# overwrite the stale binary so everything in etc/ is consistent.
sudo cp "$CFG_DIR/hmproc_adas_primary.bin"     "$ETC_DIR/hmproc_adas_primary.bin"

# ---- Step 3: Copy logging configs ----
echo ""
echo "[3/5] Copying LM and HM logging configs to $ETC_DIR ..."
sudo cp "$SCRIPT_DIR/config/lm_logging.json"         "$ETC_DIR/logging.json"
sudo cp "$SCRIPT_DIR/config/ecu_logging_config.json"  "$ETC_DIR/ecu_logging_config.json"

# ---- Step 4: Setup mini-adas working directory ----
# The Launch Manager chdir()s to dirname(binary_path) before exec.
# adas_primary reads ./etc/hm_config.json relative to that directory,
# so we must create /opt/pullpiri/bin/etc/hm_config.json.
# CONFIG_PATH points to /opt/pullpiri/etc/hmproc_adas_primary.bin (absolute),
# so copy the Bazel-generated bin there as well.
echo ""
echo "[4/5] Setting up mini-adas HM config and hmproc bin ..."
sudo mkdir -p /opt/pullpiri/bin/etc
sudo cp "$SCRIPT_DIR/config/hm_config.json" /opt/pullpiri/bin/etc/hm_config.json
sudo mkdir -p /opt/pullpiri/etc
sudo cp "$CFG_DIR/hmproc_adas_primary.bin" /opt/pullpiri/etc/hmproc_adas_primary.bin

# ---- Step 4: Launch ----
echo ""
echo "[4.5/5] Clearing Pullpiri DB files (if present)..."
# Remove shard-0 DB files (safe to run; no-op if not present)
sudo rm -rf /opt/pullpiri/bin/kvs_0_* 2>/dev/null || echo "No matching kvs_0_* files to remove"
echo ""
echo "[5/5] Starting Launch Manager daemon..."
echo "      Press Ctrl+C to stop."
echo "============================================="
echo ""

exec "$LM_BINARY"