#!/bin/bash
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
#
# run.sh - Launch the S-CORE Lifecycle Launch Manager with Pullpiri components
#
# This script builds the Pullpiri lifecycle configuration, copies the compiled
# Flatbuffer binaries and logging configs into the correct locations, and then
# starts the Launch Manager daemon.
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Determine workspace root
if [ -n "$BUILD_WORKSPACE_DIRECTORY" ]; then
    WORKSPACE_ROOT="$BUILD_WORKSPACE_DIRECTORY"
else
    # Assume we are inside examples/pullpiri_LM/
    WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
fi

BAZEL_BIN="$WORKSPACE_ROOT/bazel-bin"
LM_BINARY="$BAZEL_BIN/src/launch_manager_daemon/launch_manager"
CFG_DIR="$BAZEL_BIN/examples/pullpiri_LM/flatbuffer_out"
ETC_DIR="$WORKSPACE_ROOT/etc"

# mini-adas source workspace (relative to this repo)
MINI_ADAS_DIR="$(cd "$WORKSPACE_ROOT/../feo" && pwd)"
MINI_ADAS_LIB="$MINI_ADAS_DIR/examples/rust/mini-adas/lib"

echo "============================================="
echo "  Pullpiri Lifecycle - Build & Run"
echo "============================================="

# ---- Step 1: Build ----
echo ""
echo "[1/5] Building S-CORE Lifecycle with Pullpiri config..."
cd "$WORKSPACE_ROOT"
bazel build --config=x86_64-linux \
    //examples/pullpiri_LM:pullpiri_config \
    //src/launch_manager_daemon:launch_manager \
    //src/launch_manager_daemon/lifecycle_client_lib:lifecycle_client \
    //src/launch_manager_daemon/process_state_client_lib:process_state_client \
    //src/health_monitoring_lib:hm-lib

# ---- Step 1.5: Copy lifecycle libraries to mini-adas lib directory ----
echo ""
echo "[1.5/5] Copying lifecycle libraries to mini-adas lib directory..."
mkdir -p "$MINI_ADAS_LIB"
# Copy shared libraries built by Bazel
cp -f "$BAZEL_BIN/src/launch_manager_daemon/lifecycle_client_lib/liblifecycle_client.so" "$MINI_ADAS_LIB/" 2>/dev/null || \
cp -f "$BAZEL_BIN/src/launch_manager_daemon/lifecycle_client_lib/liblifecycle_client.a" "$MINI_ADAS_LIB/" 2>/dev/null || true
cp -f "$BAZEL_BIN/src/launch_manager_daemon/process_state_client_lib/libprocess_state_client.so" "$MINI_ADAS_LIB/" 2>/dev/null || \
cp -f "$BAZEL_BIN/src/launch_manager_daemon/process_state_client_lib/libprocess_state_client.a" "$MINI_ADAS_LIB/" 2>/dev/null || true
cp -f "$BAZEL_BIN/src/health_monitoring_lib/libhm-lib.a" "$MINI_ADAS_LIB/" 2>/dev/null || true
# Copy other required libraries
find "$BAZEL_BIN" -name "libcommon.so" -exec cp -f {} "$MINI_ADAS_LIB/" \; 2>/dev/null || true
find "$BAZEL_BIN" -name "libosal.so" -exec cp -f {} "$MINI_ADAS_LIB/" \; 2>/dev/null || true
find "$BAZEL_BIN" -name "libidentifier_hash.so" -exec cp -f {} "$MINI_ADAS_LIB/" \; 2>/dev/null || true
find "$BAZEL_BIN" -name "libphm_logging.so" -exec cp -f {} "$MINI_ADAS_LIB/" \; 2>/dev/null || true
find "$BAZEL_BIN" -name "libtimers.so" -exec cp -f {} "$MINI_ADAS_LIB/" \; 2>/dev/null || true
echo "  Lifecycle libraries copied to $MINI_ADAS_LIB"

# ---- Step 2: Build mini-adas with lifecycle feature ----
echo ""
echo "[2/5] Building mini-adas (adas_primary + adas_secondary) with lifecycle feature..."
cd "$MINI_ADAS_DIR/examples/rust/mini-adas"
LIBRARY_PATH="$MINI_ADAS_LIB" cargo build --release \
    --bin adas_primary --bin adas_secondary \
    --features "signalling_relayed_tcp,lifecycle" 2>&1 | grep -v "^warning"
cd "$WORKSPACE_ROOT"
ADAS_RELEASE="$MINI_ADAS_DIR/target/release"

# Create required directories if they don't exist
sudo mkdir -p /opt/pullpiri/bin
sudo mkdir -p /opt/pullpiri/lib
sudo mkdir -p /opt/pullpiri/etc
sudo mkdir -p /opt/pullpiri/bin/etc

# Install mini-adas binaries and shared libraries to /opt/pullpiri
sudo cp "$ADAS_RELEASE/adas_primary"   /opt/pullpiri/bin/adas_primary
sudo cp "$ADAS_RELEASE/adas_secondary" /opt/pullpiri/bin/adas_secondary
sudo chmod +x /opt/pullpiri/bin/adas_primary /opt/pullpiri/bin/adas_secondary
sudo cp "$MINI_ADAS_LIB"/lib*.so /opt/pullpiri/lib/
echo "  mini-adas binaries and .so installed to /opt/pullpiri"

# ---- Step 3: Copy flatbuffer configs ----
echo ""
echo "[3/6] Copying compiled Flatbuffer configs to $ETC_DIR ..."
mkdir -p "$ETC_DIR"
sudo cp "$CFG_DIR/lm_demo.bin"                 "$ETC_DIR/lm_demo.bin"
sudo cp "$CFG_DIR/hm_demo.bin"                 "$ETC_DIR/hm_demo.bin"
sudo cp "$CFG_DIR/hmcore.bin"                  "$ETC_DIR/hmcore.bin"
# hmproc_adas_primary.bin is regenerated by Bazel with the correct "adas_primary"
# identifier (the pre-built one from the other system uses the wrong "mini_adas_primary").
# mini-adas is a Rust app so it does NOT read CONFIG_PATH / hmproc_*.bin itself, but we
# overwrite the stale binary so everything in etc/ is consistent.
sudo cp "$CFG_DIR/hmproc_adas_primary.bin"     "$ETC_DIR/hmproc_adas_primary.bin"

# ---- Step 4: Copy logging configs ----
echo ""
echo "[4/6] Copying LM and HM logging configs to $ETC_DIR ..."
sudo cp "$SCRIPT_DIR/config/lm_logging.json"         "$ETC_DIR/logging.json"
sudo cp "$SCRIPT_DIR/config/ecu_logging_config.json"  "$ETC_DIR/ecu_logging_config.json"

# ---- Step 5: Setup mini-adas working directory ----
# The Launch Manager chdir()s to dirname(binary_path) before exec.
# adas_primary reads ./etc/hm_config.json relative to that directory,
# so we must create /opt/pullpiri/bin/etc/hm_config.json.
# CONFIG_PATH points to /opt/pullpiri/etc/hmproc_adas_primary.bin (absolute),
# so copy the Bazel-generated bin there as well.
echo ""
echo "[5/6] Setting up mini-adas HM config and hmproc bin ..."
sudo mkdir -p /opt/pullpiri/bin/etc
sudo cp "$SCRIPT_DIR/config/hm_config.json" /opt/pullpiri/bin/etc/hm_config.json
sudo mkdir -p /opt/pullpiri/etc
sudo cp "$CFG_DIR/hmproc_adas_primary.bin" /opt/pullpiri/etc/hmproc_adas_primary.bin

# ---- Step 6: Launch ----
echo ""
echo "[6/6] Starting Launch Manager daemon..."
echo "      Press Ctrl+C to stop."
echo "============================================="
echo ""

exec "$LM_BINARY"